# References from https://github.com/kairen/kubeadm-ansible/

- name: Reset k8s cluster and prepare env
  hosts: "{{ groups['all'].0 }}"
  tasks:
    - name: Reset k8s component
      shell: kubeadm reset --force
      register: reset_cluster
    - name: Disable swap
      shell: swapoff

- name: Install k8s leader
  hosts: "{{ groups['all'].0 }}"
  register: install_leader
  tasks:
    - name: install kube leader node on first node
      when: reset_cluster is succeeded
      shell: |
        kubeadm init --service-cidr {{ service_cidr }}
      register: init_cluster
    - name: copy k8s config to user
      when: init_cluster is succeeded
      copy:
        src: /etc/kubernetes/admin.conf
        dest: ".kube/config"
        owner: "{{ ansible_user | default(ansible_user_id) }}"
        group: "{{ ansible_user | default(ansible_user_id) }}"
        mode: 0755
        remote_src: true
    - name: Deploy k8s network
      shell: |
        kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
    - name: Untaint leader node
      when: untaint_leader
      shell: kubectl taint nodes --all node-role.kubernetes.io/master-
# - name: Install follower nodes
