# References from https://github.com/kairen/kubeadm-ansible/
# systemd: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/

- name: Reset k8s cluster and prepare env
  hosts: "{{ groups['all'].0 }}"
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Reset k8s component
      shell: kubeadm reset --force
      register: reset_cluster
    - name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
      shell: |
        swapoff -a
    - name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'

# https://github.com/containerd/containerd/issues/4581#issuecomment-733704174
- name: A hack to fix containerd as runtime
  become: yes
  become_user: root
  become_method: sudo
  hosts: "{{ groups['all'].0 }}"
  tasks:
    - name: Remove containerd default config file
      file:
        path: /etc/containerd/config.toml
        state: absent
    - name: Restart containerd
      systemd:
        name: containerd
        state: restarted

- name: Install k8s leader
  become: yes
  become_user: root
  become_method: sudo
  hosts: "{{ groups['all'].0 }}"
  tasks:
    - name: Install kube leader node on first node
      when: reset_cluster is succeeded
      shell: |
        kubeadm init \
          --service-cidr {{ service_cidr }} \
          --pod-network-cidr {{ pod_network_cidr }} \
          --cri-socket /run/containerd/containerd.sock
      register: init_cluster
    - name: Create home dir
      when: init_cluster is succeeded
      file:
        path: ".kube"
        owner: "{{ ansible_user | default(ansible_user_id) }}"
        group: "{{ ansible_user | default(ansible_user_id) }}"
        mode: 0755
        state: directory
    - name: Copy k8s config to user
      when: init_cluster is succeeded
      copy:
        src: /etc/kubernetes/admin.conf
        dest: ".kube/config"
        owner: "{{ ansible_user | default(ansible_user_id) }}"
        group: "{{ ansible_user | default(ansible_user_id) }}"
        mode: 0755
        remote_src: true
    - name: Deploy k8s network
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml
    - name: Untaint leader node
      when: untaint_leader
      shell: kubectl taint nodes --all node-role.kubernetes.io/master-
