- name: Get install command
  become: yes
  become_user: root
  become_method: sudo
  hosts: k8s_leader
  tasks:
    - name: Get join leader command
      shell: kubeadm token create --print-join-command
      register: worker_join_command
    - name: Save join command
      set_fact:
        cachable: true
        worker_join_command: "{{ worker_join_command.stdout }}"
    - name: Save fact to host
      add_host:
        name: leader_host
        worker_join_command: "{{ worker_join_command }}"

- name: Install k8s workers
  become: yes
  become_user: root
  become_method: sudo
  hosts: k8s_workers
  tags:
    - k8s_workers
  tasks:
    - debug:
        msg: "Deploying worker {{ inventory_hostname }} to join leader {{ kubeadm_leader_advertise_address }}"
    - debug:
        msg: "Deploying worker {{ hostvars['leader_host']['worker_join_command'] }}"
    - name: Join command
      shell: "{{ hostvars['leader_host']['worker_join_command'] }}"
      register: worker_join
    - debug:
        msg: "{{ worker_join.stdout }}"
