# References from https://github.com/kairen/kubeadm-ansible/
# systemd: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/

- name: K8s env setup
  import_playbook: k8s-common.yaml

- name: Install k8s leader
  become: yes
  become_user: root
  become_method: sudo
  hosts: k8s_leader
  tags:
    - k8s_leader
  tasks:
    - debug:
        msg: "Deploying leader to {{ kubeadm_leader_advertise_address }}"
    - name: Reset k8s component
      when: reset_current
      shell: kubeadm reset --force
    - name: Install kube leader node on first node
      command: |
        kubeadm init \
          --service-cidr {{ service_cidr }} \
          --pod-network-cidr {{ pod_network_cidr }} \
           {{ "--cri-socket /run/containerd/containerd.sock" if (use_containerd) }} \
          --apiserver-advertise-address {{ kubeadm_leader_advertise_address }} \
          {{ kubeadm_extra_flags }}
      register: init_cluster
    - debug:
        msg: "{{ init_cluster.stdout }}"
    - name: Create home dir
      when: init_cluster is succeeded
      file:
        path: ".kube"
        owner: "{{ ansible_user | default(ansible_user_id) }}"
        group: "{{ ansible_user | default(ansible_user_id) }}"
        mode: 0755
        state: directory
    - name: Copy k8s config to user
      when: init_cluster is succeeded
      copy:
        src: /etc/kubernetes/admin.conf
        dest: ".kube/config"
        owner: "{{ ansible_user | default(ansible_user_id) }}"
        group: "{{ ansible_user | default(ansible_user_id) }}"
        mode: 0755
        remote_src: true
    - name: Deploy k8s network with kube-router
      environment:
        - KUBECONFIG: /etc/kubernetes/admin.conf
      shell: |
        kubectl apply -f https://raw.githubusercontent.com/cloudnativelabs/kube-router/master/daemonset/kubeadm-kuberouter.yaml
    - name: Untaint leader node
      environment:
        - KUBECONFIG: /etc/kubernetes/admin.conf
      when: untaint_leader
      shell: kubectl taint nodes --all node-role.kubernetes.io/master-
