- name: upgrade system
  hosts: all
  tasks:
    - name: update cache
      become: yes
      apt:
        update_cache: yes
    - name: upgrade to newest version of packages
      become: yes
      apt:
        name: "*"
        state: latest
