# See more at: https://github.com/NVIDIA/gpu-operator

- name: debug
  debug:
    msg: "Installing k8s cuda operator"

- name: Add cuda k8s operator repo
  kubernetes.core.helm_repository:
    name: nvidia
    repo_url: "https://helm.ngc.nvidia.com/nvidia"

- name: Install cuda operator
  kubernetes.core.helm:
    kubeconfig: /etc/kubernetes/admin.conf
    name: gpu-operator
    chart_ref: nvidia/gpu-operator
    release_namespace: gpu-operator
    create_namespace: true
    wait: true