- name: include variables
  include_vars: ../../vars/main.yaml

- name: Reset k8s component
  when: reset_current
  shell: kubeadm reset --force
- debug:
    msg: "Deploying worker {{ inventory_hostname }} to join leader {{ kubeadm_leader_advertise_address }}"
- debug:
    msg: "Deploying worker {{ hostvars['leader_host']['worker_join_command'] }}"

- name: test if k8s is already installed
  ansible.builtin.systemd:
    name: kubelet
  register: kubelet_state

- set_fact: kubelet_up="{{ kubelet_state['status']['ActiveState'] == 'active' }}"

- name: Join command
  shell: |
    {{ hostvars['leader_host']['worker_join_command'] }} \
    {{ "--cri-socket /run/containerd/containerd.sock" if (use_containerd) }} \
    {{ kubeadm_extra_flags }}
  when: not kubelet_up
  register: worker_join
- debug:
    msg: "{{ worker_join.stdout }}"
