apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx         # Labels for the deployment, to be selected by service
spec:
  selector:
    matchLabels:
      app: nginx       # Select the labels of the pods
  template:            # Templates describe templates for container pods
    metadata:
      labels:
        app: nginx     # Describe the pod labels
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        resources:
          limits:
            cpu: 300m
          requests:
            cpu: 250m

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    nodePort: 30080
  type: NodePort

