apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-volume
  labels:
    type: nfs
    app: mysql
spec:
  volumeMode: Filesystem
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: <server address>
    path: /data/nfs/general/mysql

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-static-volume
  labels:
    type: nfs
    app: wordpress
spec:
  volumeMode: Filesystem
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: <server address>
    path: /data/nfs/general/wordpress
