# References from https://github.com/kairen/kubeadm-ansible/
# references from:
# - systemd: https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/
# - https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/install-kubeadm/
# - https://germaniumhq.com/2019/02/14/2019-02-14-Disabling-Swap-for-Kubernetes-in-an-Ansible-Playbook/
- name: update and install packages
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
- name: install kubeadm repo gpg key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present
- name: add kubeadm repo
  apt_repository:
    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    state: present
- name: install kubeadm and utilities
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - kubelet
    - kubeadm
    - kubectl

# install containerd runtime
- name: install containerd
  when: use_containerd
  include_tasks: ./containerd.yaml

# Disable swap on linux machines
- name: Disable SWAP since kubernetes can't work with swap enabled (1/2)
  shell: |
    swapoff -a
- name: Disable SWAP in fstab since kubernetes can't work with swap enabled (2/2)
  replace:
    path: /etc/fstab
    regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
    replace: '# \1'

# Load kernel module
# Reference:
# - https://stackoverflow.com/questions/55531834/kubeadm-fails-to-initialize-when-kubeadm-init-is-called
# - https://www.nocentino.com/posts/2021-12-27-installing-and-configuring-containerd-as-a-kubernetes-container-runtime/
- name: Load overlay module
  modprobe:
    name: overlay
    state: present
- name: Load bf_netfilter module
  modprobe:
    name: br_netfilter
    state: present
- name: Set Bridge call
  shell:
    cmd: echo 1 > /proc/sys/net/bridge/bridge-nf-call-iptables
- name: Set bridge.bridge-nf-call-iptables
  shell:
    cmd: echo 1 > /proc/sys/net/ipv4/ip_forward
- name: Update sysctl
  shell:
    cmd: sudo sysctl --system
