
- name: Find if helm exists
  shell: helm
  register: helm

- name: Install helm
  when: helm.rc != 0
  shell: |
    curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash

- name: Deploy NFS and k8s storage provider
  include_tasks: nfs.yaml