- name: Install common tools and utilities
  hosts: k8s
  roles:
    - k8s/k8s_common

- name: Install k8s leader
  hosts: k8s_leader
  roles:
    - k8s/k8s_leader

- name: Install k8s worker
  hosts: k8s_worker
  roles:
    - k8s/k8s_worker
