# Tasks to perform after k8s installation, e.g. setting up NFS, cuda, etc

- import_playbook: nfs.yaml

- name: Install k8s NFS operator
  hosts: k8s_leader
  vars:
    server_dirs:
      - /data/nfs/general
  roles:
    - helm/nfs