- name: Install NFS server
  hosts: nfs_server
  tags:
    - nfs
  vars:
    nfs_server_dirs:
      - /data/nfs/general
  roles:
    - nfs/nfs_server

- name: Mount on NFS clients
  hosts: nfs
  tags:
    - nfs
  vars:
    nfs_client_dirs:
      - server_path: /data/nfs/general
        client_path: /data/nfs/mount
  roles:
    - nfs/nfs_client